version: "3.2"

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db

  django:
    restart: always
    container_name: django
    command: bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./config/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  react:
    restart: always
    command: npm start
    container_name: react
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - django

