#version: "3"
#services:
#  mongodb:
#    environment:
#      MONGO_INITDB_DATABASE: mydatabase
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
#    hostname: mongodb
#    image: mongo
#    ports:
#      - "27017:27017"
#    volumes:
#      - ./data-db:/data/db
#
#  django:
#    build: ./config
#    command: "python manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - .:/django
#    ports:
#      - "8000:8000"
#    links:
#      - mongodb

version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data-db:/data/db
    ports:
      - '27017:27017'
    restart: unless-stopped

  config:
    build: ./config
    restart: always
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - ./config:/config
    ports:
      - '8000:8000'
    links:
      - mongodb
#    depends_on:
#      - db
#
#  db:
#    image: mongo:4.1.8-xenial
#    container_name: db
#    restart: always
#    volumes:
#      - dbdata:/data/db
#    networks:
#      - app-network
##  mongodb:
##      image: mongo:latest
##      restart: always
##      environment:
##        MONGO_INITDB_ROOT_USERNAME: root
##        MONGO_INITDB_ROOT_PASSWORD: mongoadmin
##        MONGO_INITDB_DATABASE: dbdemo
##      volumes:
##        - ./data-db:/data/db
##      ports:
##        - '27017:27017'
#
##  mongodb:
##    image: mongo:latest
##    restart: always
##    volumes:
##        - ./data-db:/data/db
##    ports:
##      - '27017:27017'