version: '3.1'
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: demo
    ports:
      - 27017:27017

  web:
    build: ./config
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./config:/config
    ports:
      - 8000:8000
    links:
      - mongodb
#version: '3'
#
##volumes:
##  init-db:
##  data-db:
#
#services:
##  mongodb:
##    image: mongo
##    restart: always
##    container_name: mongodb
##    environment:
##      MONGO_INITDB_ROOT_USERNAME: root
##      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
##      MONGO_INITDB_DATABASE: mongodb
##    volumes:
##      - ./data-db:/data/db
##    ports:
##      - '27017:27017'
#
#
#  config:
#    build: ./config
#    restart: always
#    command: python3 manage.py runserver
#    volumes:
#      - ./config:/config
#    ports:
#      - '8000:8000'
##    links:
##      - mongodb
#    depends_on:
#      - migration
#
#  migration:
#    build: ./config
#    command: python manage.py migrate
#    volumes:
#      - ./config:/config
##    links:
##      - mongodb
#    depends_on:
#      - make_migrations
#
#  make_migrations:
#    build: ./config
#    command: python manage.py makemigrations
#    volumes:
#      - ./config:/config
##    links:
##      - mongodb
##    depends_on:
##      - mongodb